# Generated by Django 4.1 on 2023-01-31 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Nome')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Tipo de conta',
                'verbose_name_plural': 'Tipos de conta',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, default=0.0, max_length=10, verbose_name='Saldo Bancário')),
                ('archived', models.BooleanField(default=False, verbose_name='Arquivado')),
                ('canceled', models.BooleanField(default=False, verbose_name='Cancelado')),
                ('default', models.BooleanField(default=False, verbose_name='Conta Principal')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['bank'],
            },
        ),
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('logo', models.FileField(blank=True, max_length=200, null=True, upload_to='bank_logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.FileField(blank=True, max_length=200, null=True, upload_to='attachments/', verbose_name='Anexos')),
                ('date_transaction', models.DateField(verbose_name='Data da Transação')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('installment', models.IntegerField(blank=True, null=True, verbose_name='Parcela')),
                ('note', models.CharField(max_length=500, verbose_name='Observação')),
                ('paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('recurring', models.BooleanField(default=False, verbose_name='Repete')),
                ('select', models.CharField(choices=[('Diariamente', 'Diariamente'), ('Semanalmente', 'Semanalmente'), ('Mensalmente', 'Mensalmente'), ('Anualmente', 'Anualmente')], default='', max_length=12, verbose_name='Frequência')),
                ('total_installments', models.IntegerField(blank=True, null=True, verbose_name='Parcelas Totais')),
                ('type', models.CharField(choices=[('Receitas', 'Receitas'), ('Despesas', 'Despesas')], default='', max_length=10, verbose_name='Despesas e Receita')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks_accounts.account_types', verbose_name='Tipo de conta')),
                ('accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks_accounts.accounts', verbose_name='Conta')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks_accounts.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['description'],
            },
        ),
        migrations.AddField(
            model_name='accounts',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='banks_accounts.banks', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='banks_accounts.account_types', verbose_name='Tipo da conta'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
