# Generated by Django 4.1 on 2023-02-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_category_alter_transactions_category'),
        ('banks_accounts', '0002_delete_transactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
