# Generated by Django 4.1 on 2023-02-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks_accounts', '0003_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='default',
            new_name='main',
        ),
    ]
