# Generated by Django 4.1 on 2023-02-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks_accounts', '0005_alter_accounts_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='amount',
            field=models.CharField(blank=True, default=0.0, max_length=200, verbose_name='Saldo Bancário'),
        ),
    ]
