# Generated by Django 4.1.6 on 2023-02-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks_accounts', '0006_alter_accounts_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='logo',
            field=models.FileField(blank=True, default=None, max_length=200, null=True, upload_to='bank_logo'),
        ),
    ]
