# Generated by Django 4.1.6 on 2023-02-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks_accounts', '0008_alter_account_types_name_alter_banks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_types',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='Nome'),
        ),
    ]
