# Generated by Django 5.0 on 2023-12-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks_accounts', '0009_alter_account_types_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banks',
            name='logo',
        ),
    ]
