# Generated by Django 5.0 on 2024-03-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks_accounts', '0010_remove_banks_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Saldo Bancário'),
        ),
    ]
