# Generated by Django 4.1 on 2023-01-31 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks_accounts', '0002_delete_transactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.FileField(blank=True, max_length=200, null=True, upload_to='attachments/', verbose_name='Anexos')),
                ('date_transaction', models.DateField(verbose_name='Data da Transação')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('installment', models.IntegerField(blank=True, null=True, verbose_name='Parcela')),
                ('note', models.CharField(max_length=500, verbose_name='Observação')),
                ('paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('recurring', models.BooleanField(default=False, verbose_name='Repete')),
                ('select', models.CharField(choices=[('Diariamente', 'Diariamente'), ('Semanalmente', 'Semanalmente'), ('Mensalmente', 'Mensalmente'), ('Anualmente', 'Anualmente')], default='', max_length=12, verbose_name='Frequência')),
                ('total_installments', models.IntegerField(blank=True, null=True, verbose_name='Parcelas Totais')),
                ('type', models.CharField(choices=[('Receitas', 'Receitas'), ('Despesas', 'Despesas')], default='', max_length=10, verbose_name='Despesas e Receita')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks_accounts.account_types', verbose_name='Tipo de conta')),
                ('accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks_accounts.accounts', verbose_name='Conta')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks_accounts.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['description'],
            },
        ),
    ]
