# Generated by Django 4.1 on 2023-01-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactions_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='value',
            field=models.CharField(blank=True, default='0,0', max_length=20, verbose_name='Valor'),
        ),
    ]
