# Generated by Django 4.1 on 2023-02-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transactions_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='value',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valor'),
        ),
    ]
