# Generated by Django 4.1.6 on 2023-03-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_category_alter_transactions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='date_paid',
            field=models.DateField(default='2023-03-16', verbose_name='Data de Realização do pagamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='installment',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Parcela'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='total_installments',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Parcelas Totais'),
        ),
    ]
