# Generated by Django 4.1.6 on 2023-03-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transactions_date_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date_paid',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Realização do pagamento'),
        ),
    ]
