# Generated by Django 4.1.6 on 2023-03-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transactions_date_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='installment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parcela'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='total_installments',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parcelas Totais'),
        ),
    ]
