# Generated by Django 4.1.6 on 2023-03-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_transactions_installment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='installment',
        ),
    ]
