# Generated by Django 4.1.6 on 2023-03-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_remove_transactions_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Categoria'),
        ),
    ]
