# Generated by Django 4.1.6 on 2023-03-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='date_paid',
        ),
    ]
