# Generated by Django 5.0 on 2023-12-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_transactions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='select',
            field=models.CharField(choices=[('', '---------'), ('Diariamente', 'Diariamente'), ('Semanalmente', 'Semanalmente'), ('Mensalmente', 'Mensalmente'), ('Anualmente', 'Anualmente')], default='', max_length=12, verbose_name='Frequência'),
        ),
    ]
