# Generated by Django 5.0 on 2024-01-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_remove_transactions_paid_installments'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='paid_installment',
            field=models.PositiveIntegerField(default=0, verbose_name='Parcela paga'),
        ),
    ]
