# Generated by Django 5.0 on 2024-01-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_transactions_paid_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='paid_installment',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Parcela paga'),
        ),
    ]
