# Generated by Django 5.0 on 2024-03-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_alter_transactions_paid_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='value',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Valor'),
        ),
    ]
